GET http://localhost:8070/api/user/produce

###

GET http://localhost:8070/api/user/1

###

GET http://localhost:8070/api/user?email=

###

POST http://localhost:8070/api/user
Content-Type: application/json

< ./sample.json
